### ISSUE TITLE
update inits and fini diag_msg on every call

### ISSUE THREAD

**Issue by bjv-capra** [micro-ROS/micro_ros_diagnostics#11]
As you can see [here](https://github.com/micro-ROS/micro_ros_diagnostics/blob/feature/un-string-ify/micro_ros_diagnostic_updater/src/micro_ros_diagnostic_updater/micro_ros_diagnostic_updater.c#L159), the message is allocated and deallocated on every call. IMHO, the message should be initialized once, and maybe be part of the updater struct, thus, the `init` could be called once when doing it for the updater, and the `fini` when the updater is terminated.

**Comment by bjv-capra** [comment]
I can see that the updater struct struct already has a message member that doesn't seem to be used anywhere, https://github.com/micro-ROS/micro_ros_diagnostics/blob/c603b0bc1c2748f25a79a1edc78ae350b21654e7/micro_ros_diagnostic_updater/include/micro_ros_diagnostic_updater/micro_ros_diagnostic_updater.h#L45 

maybe it was thought for this purpose?

**Comment by norro** [comment]
Yes, this was the purpose, it was just not properly used, yet. :)

**Comment by bjv-capra** [comment]
@norro could you review https://github.com/micro-ROS/micro_ros_diagnostics/pull/13 ?
