### ISSUE TITLE
Diagnostic and diagnostics

### ISSUE THREAD

**Issue by bjv-capra** [micro-ROS/micro_ros_diagnostics#14]
This repo is called `micro_ros_diagnostic**s**`, however, some of the internal packages are called `micro_ros_diagnostic_`, without the trailing **s**, furthermore, micro_ros_common_diagnostics, doesn't follow the naming convention and also has the trailing **s**

I know this is WIP, but aligning it would be great. I noticed this while trying to script the special build for now.

**Comment by norro** [comment]
@bjv-capra Can you elaborate where this causes troubles?

I see that it doesn't seem to be a general naming convention in ROS/ROS2 to have all packages prefixed with the repo name, see https://github.com/ros/diagnostics/ or https://github.com/ros2/launch_ros/ for example. I understand that this would be a convenience for automation?

**Comment by bjv-capra** [comment]
It doesn't cause problem, it's more about it not being fully consistent. On that repo, the packages are called simply diagnostic_ (amongst other packages) rather than ros_diagnostics, here it seemed different. Simply because of it...we can close it otherwise.
