### ISSUE TITLE
Support multiple HW id per updater

### ISSUE THREAD

**Issue by bjv-capra** [micro-ROS/micro_ros_diagnostics#16]
As a user, I'd like to be able to utilize the same updater to send information from different hardware devices.

As a use case, I have a board that collects information coming in from N different peripherals devices. This board is my micro-ROS client and runs a diagnostic_updater. Each peripheral may have up to M valuable information I may want to report up. Thus, I'd like to be able to also indicate to what HW_id a task belongs.

Does this use case make sense?

**Comment by bjv-capra** [comment]
I'll try to create a PR with a draft for this soon.

**Comment by bjv-capra** [comment]
Okay, sorry for the delay. I had to go through the documentation of Diagnostics and the RFC to better understand what you're suggesting as I was a little bit confused.

- From [the REP](https://www.ros.org/reps/rep-0107.html#id18), the hardware_id is the unique identifier of the hw (serial number). Thus, in the future, we may need to remove the ability to use a lookup table and have a predefined char[max_size] hardware_id. Where max_size can be set as a CMAKE option. My mistake was to think this id actually was simply a component identifier such as "this is a motor", not a "this is THIS specific piece".
- Updater, although I'm not a fan of the name, this is what actually indicates what type of component is. Thus, "this is a motor".

So, the current design I think, is on the correct track (except the hardware_id).

What I wanted to do, or have the ability to do is not to be forced to have multiple updaters on my embedded system, rather only one. The main reason why I wanted this, is because the call to `rclc_diagnostic_updater_init` consumes 375 words out of my stack (quite a bit) while creating a simple publisher only consumes 27 words. This needs to be addressed.

On the other hand, my approach would require more tasks which I believe would be less expensive than creating multiple updaters.

To sum, I think we have to add a few options to the API which I don't think to need to be exclusive

1. A user predefines(cmake option) how many MAX updaters it will want to have (1->N). Then the user creates one updater per hw component (indicating the hw_id at the same time).
2. A user predefines(cmake option) how many MAX tasks it may want to have (1->N).
3. A user may have an updater to send updates for multiple devices. However, for this purpose, the updater shouldn't be init'ed with an id (nor hw id), and the task would carry the updater_id and the hw_id. This leaves a loophole where the user may assign the same ID to an updater and also pass it to a task, however, this should be up to the user to define.

**Comment by norro** [comment]
I think having fixed maxima of updaters and tasks via cmake is definitely fair for a uc setup. I also think that a cmake option for the hardware_id (not only it's size) could make sense, as the ID should be fix for one particular uc anyway. don't you think?

I also think that restricting ourselves to one _updater_ (read: `micro_ros_diagnostic_updater`) per uc is fair. To still simulate/pretend different _updaters_ (read: _logical_ ROS 2 diagnostic updaters), moving the updater ID to the tasks makes sense as well.

I think, though, that we should do either 1.+.2. **or** 2.+3. to not be too confusing.
So _either_ define max number of updaters and tasks via cmake (so actually allowing several updaters per device) and then having the updater ID in the updater **or** having just one uros updater per uc and then simulate different logical updaters by moving the updater to the tasks.

**Comment by bjv-capra** [comment]
I can provide you a live example, we have one uc that concentrates all peripherals from our platform (coming via different protocols), each peripheral has its own hardware_id (read: serial number). Hence, I'd like to pass the hardware_id + updater_id (read: id used to lookup the internal name of the device). However, I'd like to do this utilizing the least amount of memory possible, which seemed to be having X tasks and 1 updater. This would be 2+3 and not 1+2.

**Comment by norro** [comment]
Sounds good to me!
