### ISSUE TITLE
Make Bart maintainer

### ISSUE THREAD

**Issue by norro** [micro-ROS/micro_ros_diagnostics#34]
- [x] Provide according access to https://github.com/micro-ROS/micro_ros_diagnostics
- [ ] Provide according access to https://github.com/ros2-gbp/micro_ros_diagnostics-release
- [x] Update package manifests

**Comment by norro** [comment]
Made Bart maintainer of https://github.com/micro-ROS/micro_ros_diagnostics

**Comment by norro** [comment]
Access to https://github.com/ros2-gbp/micro_ros_diagnostics-release requested with Steven! from OSRF.

**Comment by norro** [comment]
Steven just confirmed that you got access to https://github.com/ros2-gbp/micro_ros_diagnostics-release @bjv-capra Can you check? 
I think clicking the edit button here https://github.com/ros2-gbp/micro_ros_diagnostics-release/blob/master/README.md for example should tell you (if you miss write permissions, you will get a warning from github, I suppose).

If you got the permissions, you can close this issue.

**Comment by norro** [comment]
@bjv-capra friendly ping. :)

**Comment by bjv-capra** [comment]
Sorry, I can actually click the edit button. So I'll close this issue :)
