### ISSUE TITLE
Feature request: Logging like ros2 node.get_logger()

### ISSUE THREAD

**Issue by PaddyCube** [micro-ROS/micro_ros_diagnostics#6]
A ROS2 node provides a handy interface for log messages. Something like node.get_logger().info(). You all know we can view these messages in rqt and other tools.

It seems that such a function is not availabe in micro-ros

**Comment by norro** [comment]
Hi @PaddyCube, this seems to be a feature request of the client library, not the diagnostics framework. Please consider opening a feature request for https://github.com/ros2/rclc/.

However, have you had a look at the error and warning macros in rclc, i.e. [rclc/types.h#L39-L63](https://github.com/ros2/rclc/blob/master/rclc/include/rclc/types.h#L39-L63) Is this somewhat what you're looking for?

**Comment by PaddyCube** [comment]
Thanks, I've created a new one here
https://github.com/micro-ROS/rclc/issues/77
